trigger:
- main

pool:
  name: default

steps:
# Step 1: Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# Step 2: Install dependencies and build
- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

# Step 3: Run code linting (optional, for code quality checks)
- script: |
    npm run lint
  displayName: 'Run Linter'

# Step 4: Run tests (optional, based on your project setup)
- script: |
    npm test
  displayName: 'Run Unit Tests'

# Step 5: Copy necessary files to Artifact Staging Directory
- script: |
    mkdir -p $(Build.ArtifactStagingDirectory)
    xcopy *.* ./* $(Build.ArtifactStagingDirectory)
  displayName: 'Copy files to Artifact Staging Directory'

# Step 6: Publish build artifacts
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'
