trigger:
- main

pool:
  vmImage: 'windows-latest'  # Use Windows agent

steps:
# Step 1: Clear Node.js Cache (Windows Version)
- powershell: |
    if (Test-Path "$(Agent.ToolsDirectory)\NodeJs") {
        Remove-Item -Recurse -Force "$(Agent.ToolsDirectory)\NodeJs"
        Write-Host "Node.js cache cleared."
    } else {
        Write-Host "No Node.js cache to clear."
    }
  displayName: 'Clear Node.js Cache (Windows)'

# Step 2: Install Node.js
- task: NodeTool@1  # Use NodeTool@1 or @0 if necessary
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# Step 3: Verify Node.js Installation
- powershell: |
    node --version
    npm --version
  displayName: 'Verify Node.js and npm Installation'

# Step 4: Install Dependencies and Build
- powershell: |
    npm install
    npm run build
  displayName: 'npm install and build'

# Step 5: Run Linting (Optional)
- powershell: |
    npm run lint
  displayName: 'Run Linter'

# Step 6: Run Unit Tests (Optional)
- powershell: |
    npm test
  displayName: 'Run Unit Tests'

# Step 7: Prepare Artifact Staging Directory
- powershell: |
    New-Item -ItemType Directory -Force -Path "$(Build.ArtifactStagingDirectory)"
    Copy-Item -Recurse -Path .\* -Destination "$(Build.ArtifactStagingDirectory)\"
  displayName: 'Copy files to Artifact Staging Directory'

# Step 8: Publish Build Artifacts
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'